# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VoiceStorm Demos
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is provided as a means to jump start your development with the VoiceStorm API &amp; 
  SDK by Dynamic Signal. You will find various examples above that will hopefully help demonstrate 
  potential use cases.
url: "http://shawnphoffman.com" # the base hostname & protocol for your site
twitter_username: dynamicsignal
github_username:  shawnphoffman
github_repo: "https://github.com/shawnphoffman/VoiceStorm-Demos"
api_docs: "https://dev.voicestorm.com"

# Build settings
markdown: kramdown
